version: "3.9"

services:
  wtd-client:
    container_name: wtd-client
    build:
      context: .
      dockerfile: ./apps/client/Dockerfile
    expose: ["5173"]
    restart: unless-stopped

  wtd-server:
    container_name: wtd-server
    build:
      context: .
      dockerfile: ./apps/server/Dockerfile
    environment:
      - PORT=8080
    expose: ["8080"]
    restart: unless-stopped

  caddy:
    image: caddy:2-alpine
    container_name: wtd-caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy-data:/data
      - caddy-config:/config
      # mount your built client
      - ./apps/client/dist:/srv/static:ro
    depends_on:
      - wtd-server
    networks:
      - default

volumes:
  caddy-data:
  caddy-config:
