export type PromptLanguage = "fi";

export class DrawingPrompts {
  /**
   * Get a random drawing prompt for the specified language.
   */
  static getPrompt(lang: PromptLanguage) {
    const prompts = DrawingPrompts.prompts[lang];
    const randomIndex = Math.floor(Math.random() * prompts.length);
    return prompts[randomIndex]!;
  }

  /**
   * Get a series of random prompts while avoiding duplicates.
   */
  static getPrompter(lang: PromptLanguage) {
    const pool = [...DrawingPrompts.prompts[lang]];
    return {
      getNextPrompt() {
        // Refill pool if empty
        if (pool.length === 0) {
          pool.push(...DrawingPrompts.prompts[lang]);
        }

        // Select random prompt from pool and remove it
        const randomIndex = Math.floor(Math.random() * pool.length);
        return pool.splice(randomIndex, 1)[0]!;
      },
    };
  }

  /**
   * Drawing prompts in different languages.
   */
  static prompts: Record<PromptLanguage, string[]> = {
    fi: [
      "Vesimeloni kypärä",
      "Batman saunassa",
      "Spagettihirviö",
      "Ritari ilman hevosta",
      "Pehmolelu presidenttinä",
      "Sieni sateenvarjona",
      "Discopallo metsässä",
      "Donald Duck ilman housuja",
      "Jääkarhu hellehatulla",
      "Gameboy, josta kasvaa kukka",
      "UFO liikenneympyrässä",
      "Pikachu kahvikupissa",
      "Jalkapallo jonka sisällä on kissa",
      "Susi aurinkolaseissa",
      "Valas lentokoneessa",
      "Krokotiili soittaa pianoa",
      "Harry Potter sähköpotkulaudalla",
      "T-Rex ottaa selfien",
      "Kaktus joulukuusena",
      "Muumipeikko skeittilaudalla",
      "Juustopala, jossa on ovi ja ikkuna",
      "Hämähäkki näppäimistöllä",
      "Shrek kukkakedolla",
      "Lego-ukko ratsastaa etanalla",
      "Zombie juoksee maratonia",
      "Kaljatölkki viiksillä",
      "Angry Birds ilman nokkaa",
      "Salami-lonkero",
      "Kahvinkeitin jolla on jalat",
      "Mario jäätelötötterössä",
      "Sähkökitara porkkanasta",
      "Vohveliraudasta tehty avaruusalus",
      "Homer Simpson marjapuskassa",
      "Kuningas ilman kruunua",
      "Tomaatti skeittilaudalla",
      "Rölli lentokoneessa",
      "Silmälasit banaanilla",
      "Hämähäkkimies pyöräilee",
      "Kissa avaruuspuvussa",
      "Talo ilmapalloilla",
      "Chewbacca juo kahvia",
      "Jääkaappi jolla on jalat",
      "Pelikonsoli sateenvarjona",
      "Darth Vader uimarenkaassa",
      "Jättiläiskenkä talona",
      "Salama syö suklaata",
      "Kivi jolla on kruunu",
      "Yoda soittaa viulua",
      "Kana käyttää tietokonetta",
      "Tyrannosaurus syö hotdogia",
      "Polkupyörä pizzapyörillä",
      "Simpsons-sohva metsässä",
      "Muumimamma skeittaa",
      "R2-D2 lumipallotaistelussa",
      "Hattu täynnä sammakoita",
      "Zelda keittämässä keittoa",
      "Lentävä kirjahylly",
      "Baseball-pallo jolla on silmät",
      "Pepsi-tölkki ratsastaa karhulla",
      "Shakkihevonen oikeana hevosena",
      "Omena avaruuskypärässä",
      "Minecraft-kuutio meressä",
      "Bart Simpson hiihtämässä",
      "Laiva tehty juustosta",
      "Avokado jolla on aurinkolasit",
      "Luokkahuone merenpohjassa",
      "Pyramidi pizzasta",
      "Dinosaurus soittaa rumpuja",
      "Kissa piilossa kahvikupissa",
      "Pac-Man syö hattaraa",
      "Lumiukko aurinkotuolissa",
      "Pringles-putkesta tehty raketti",
      "Koirankoppi avaruudessa",
      "Röllipeikko tietokoneella",
      "Kello, jolla on jalat",
      "Joulukuusi surffilaudalla",
      "Peili, josta tulee kala",
      "Auto donitseista",
      "Krokotiili luistelee",
      "Sormus jolla on kasvot",
      "Karhu juo limsaa",
      "Super Mario trampoliinilla",
      "Kuumailmapallo banaanista",
      "Muumitalo jäävuorella",
      "Robotin pää popkorneista",
      "Spiderman hämähäkinverkossa riippukeinuna",
      "Nintendo-ohjain veneenä",
      "Jättimäinen porkkana sillan tilalla",
      "Susi juo energiajuomaa",
      "Lego-palikka lentokoneena",
      "Donald Trump muumitalossa",
      "Kirja, joka ui vedessä",
      "Nalle Puh lentokoneessa",
      "Ikkuna, josta kasvaa puu",
      "Zombi käyttää älypuhelinta",
      "Jedi syö pizzaa",
      "Karuselli suklaapatukoista",
      "Karhu hiihtohississä",
      "Sämpylä, jossa on silmät",
      "Hulk kutoo villasukkaa",
      "Pöllö soittaa rumpuja",
      "Stormtrooper kalastamassa",
      "Kirahvi kuumailmapallossa",
      "Delfiini skeittilaudalla",
      "Shrek syö nuudeleita",
      "Sammakko pukeutunut prinssiksi",
      "Auto, jossa on siivet",
      "Yoda ratsastaa kanalla",
      "Kissa pelaa Nintendo Switchiä",
      "Vesitorni jäätelönä",
      "Pyramidi Lego-palikoista",
      "Spider-Man kahvilassa",
      "Ankka ajaa moottoripyörää",
      "Kahvikuppi sateenvarjona",
      "Lentävä sohva",
      "Darth Vader haravoi lehtiä",
      "Muumipeikko syö sushia",
      "Joulupukki skeittaa",
      "Palapeli, jossa on kasvot",
      "Robotin pää sipulista",
      "Homer Simpson ratsastaa lampulla",
      "Panda pelaa pingistä",
      "T-Rex tanssii balettia",
      "Lentävä sateenvarjo sateessa",
      "Rölli ratsastaa etanalla",
      "Donald Duck syö hotdogin",
      "Gameboy skeittilaudalla",
      "Zombie ajaa autoa",
      "Susi kantaa sateenvarjoa",
      "Jääkarhu uimarenkaassa",
      "Kirja lentokoneena",
      "Pelikonsoli kahvikuppina",
      "Mickey Mouse trampoliinilla",
      "Yoda tekee lumienkeleitä",
      "Bart Simpson ratsastaa krokotiililla",
      "Vohveliraudasta tehty piano",
      "Panda lentää raketilla",
      "Hämähäkki ratsastaa polkupyörällä",
      "Sämpylä aurinkolaseissa",
      "Talo, joka on banaanin muotoinen",
      "Dinosaurus ratsastaa yksipyöräisellä",
      "Shakkihevonen skeittilaudalla",
      "Pac-Man ajaa bussia",
      "Sonic syö donitseja",
      "Toad pelaa jalkapalloa",
      "R2-D2 ui järvessä",
      "Angry Bird lukee kirjaa",
      "Muumimamma ajaa traktoria",
      "Homer Simpson grillaa makkaraa",
      "Valas jongleeraa palloilla",
      "Mona Lisa pyöräilee",
      "Zombie soittaa kitaraa",
      "Minecraft Steve lumisodassa",
      "T-Rex pelaa lautapeliä",
      "Pyramidi ilmapalloista",
      "Simpsons-perhe veneessä",
      "Karhu soittaa rumpuja",
      "Super Mario syö nuudeleita",
      "Chewbacca ajaa bussilla",
      "Sienihattu sateenvarjona",
      "Krokotiili lentää avaruuteen",
      "Zelda soittaa pianoa",
      "Pikachu syö jäätelöä",
      "Darth Vader skeittilaudalla",
      "Bart Simpson syö kebabia",
      "Muumitalo taivaalla",
      "Joulupukki ratsastaa tiikerillä",
      "Yoda juo limsaa",
      "Kissa lumilautailussa",
      "Donald Duck tanssii discossa",
      "Shrek ui järvessä",
      "Pelikonsoli jolla on kasvot",
      "Pac-Man polkupyörällä",
      "Spiderman hiihtää",
      "Lego-palikka sohvana",
      "Susi skeittaa",
      "Homer Simpson nukkuu riippumatossa",
      "Jedi käyttää sateenvarjoa",
      "Rölli piirtää taululle",
      "Zombie lentää helikopterilla",
      "Muumipeikko tekee nuotiota",
      "Angry Bird pelaa koripalloa",
      "Kahvikuppi jossa on silmät",
      "T-Rex ratsastaa kamelilla",
      "Panda hiihtää",
      "Yoda syö hotdogia",
      "Bart Simpson pelaa tietokonetta",
      "Simpsons-sohva lentää",
      "Chewbacca soittaa viulua",
      "Lumiukko skeittilaudalla",
      "Hämähäkki juo kahvia",
      "Mona Lisa skeittaa",
      "Shrek hiihtää",
      "Super Mario nukkuu riippumatossa",
      "Pelikonsoli lentää",
      "Zelda syö pizzaa",
      "Pac-Man skeittilaudalla",
      "Muumimamma juo kahvia",
      "Jääkaappi täynnä kaloja",
      "Talo veden alla",
      "Polkupyörä sateenvarjona",
      "Puhelin, jolla on siivet",
      "Aurinko jolla on parta",
      "Kynä kasvaa puuksi",
      "Puu kävelee kengissä",
      "Sateenkaari muuttuu sillaksi",
      "Kello jolla on hattu",
      "Hammasharja soittaa kitaraa",
      "Vesitorni kurkistaa ikkunasta",
      "Juna kulkee vuoren sisällä",
      "Kengät kasvavat maasta",
      "Sieni jolla on naama",
      "Pilvi syö jäätelöä",
      "Kirja muuttuu linnuksi",
      "Portaat taivaaseen",
      "Ovi keskellä metsää",
      "Laatikko jossa on jalat",
      "Kala kävelee maalla",
      "Talo hatun sisällä",
      "Kissa sateenvarjon alla",
      "Kakku, josta kasvaa kukkia",
      "Talo jääpalan sisällä",
      "Lehmän näköinen pilvi",
      "Joki kulkee taivaalla",
      "Kivi jolla on silmät",
      "Sipuli pyöräilee",
      "Porkkana soittaa rumpuja",
      "Lamppu kasvaa maasta",
      "Silta, joka on tehty kirjoista",
      "Vuori, jonka päällä on tuoli",
      "Jäätelö sulaa lattialle",
      "Reppu juoksee",
      "Kynttilä hymyilee",
      "Hattu lentää taivaalla",
      "Auto jossa on jalat",
      "Sänky kelluu meressä",
      "Lusikka ratsastaa haarukalla",
      "Tuoli jolla on parta",
      "Juna ajaa sateenkaarella",
      "Bussi soittaa torvea",
      "Kaktus juo vettä",
      "Leipä lentää taivaalla",
      "Kirahvi asuu jääkaapissa",
      "Sipuli jolla on kruunu",
      "Aurinkokello hymyilee",
      "Kynttilä polttaa jäätä",
      "Kello kasvaa puussa",
      "Linnunpesä sateenvarjossa",
      "Metsä veden alla",
      "Tikkaat ilman päätepistettä",
      "Talo kasvot ikkunoina",
      "Aurinko ratsastaa pilvellä",
      "Vesimeloni avautuu kuin kirja",
      "Kissa kasvaa kukkaruukusta",
      "Koira nukkuu pilven päällä",
      "Kahvikuppi jolla on kädet",
      "Talvi keskellä kesää",
      "Kello sulaa pöydälle",
      "Puhelin kasvaa maasta",
      "Ovi jonka takana on meri",
      "Puussa kasvaa kengät",
      "Vuori jolla on silmät",
      "Kaktus soittaa kitaraa",
      "Jääpuikko juoksee",
      "Silta joka johtaa ilmaan",
      "Laatikko avautuu sateenkaareksi",
      "Polkupyörä jolla on silmät",
      "Sieni kasvaa sateenvarjosta",
      "Järvi keskellä taivasta",
      "Kello ratsastaa kilpikonnalla",
      "Paperilennokki jolla on siivet",
      "Kynttilä kasvaa kukkaruukusta",
      "Vuori jonka sisällä on talo",
      "Omena jolla on jalat",
      "Kivi jolla on siivet",
      "Jääkaappi pyörillä",
      "Reppu jolla on kasvot",
      "Puhelin jolla on jalat",
      "Kala ui taivaalla",
      "Pilvi jolla on sateenvarjo",
      "Lusikka jolla on silmät",
      "Puu jolla on kädet",
      "Kahvikuppi jolla on siivet",
      "Kynttilä jolla on jalat",
      "Vuori muuttuu sateenkaareksi",
      "Silta kasvaa metsästä",
      "Auto ui järvessä",
      "Juna jolla on kasvot",
      "Kirja jonka sisällä on metsä",
      "Kello jolla on kädet",
      "Talo joka kävelee",
      "Kaktus jolla on aurinkolasit",
      "Vuori jolla on hattu",
      "Lusikka jonka sisällä on meri",
      "Puu joka juoksee",
      "Sateenkaari jossa on ovia",
      "Omena jolla on silmät",
      "Kivi joka hymyilee",
    ],
  };
}
